# Generated by Django 2.1 on 2018-10-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments_text', models.TextField()),
                ('Comments_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Comments_table',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_url', models.URLField()),
                ('Video_name', models.CharField(max_length=200)),
                ('Video_properties', models.TextField()),
                ('Video_date', models.DateField(auto_now_add=True)),
                ('Video_likos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Video_table',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='Comments_Video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Video'),
        ),
    ]
